# Generated by Django 4.2.2 on 2023-06-16 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0003_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='evento_participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
